export const TEMAS_DADOS = [
  { valor: 'theme-glass', nome: 'Vidro' },
  { valor: 'theme-solid', nome: 'Sólido' },
  { valor: 'theme-neon', nome: 'Neon' },
  { valor: 'theme-obsidian', nome: 'Obsidiana' },
  { valor: 'theme-weathered-oak', nome: 'Carvalho Envelhecido' },
  { valor: 'theme-carrara-marble', nome: 'Mármore de Carrara' },
  { valor: 'theme-verdigris-copper', nome: 'Cobre Oxidado' },
  { valor: 'theme-bioluminescent', nome: 'Bioluminescente' },
  { valor: 'theme-frosted-glacier', nome: 'Geleira Congelada' },
  { valor: 'theme-volcanic-basalt', nome: 'Basalto Vulcânico' },
  { valor: 'theme-ancient-parchment', nome: 'Pergaminho Antigo' },
  { valor: 'theme-jade-imperium', nome: 'Jade Imperial' },
  { valor: 'theme-starry-night', nome: 'Noite Estrelada' },
  { valor: 'theme-arcane-leyline', nome: 'Linha Arcana' },
  { valor: 'theme-spirit-wisp', nome: 'Espírito Errante' },
  { valor: 'theme-phoenix-ember', nome: 'Brasa da Fênix' },
  { valor: 'theme-void-dweller', nome: 'Habitante do Vazio' },
  { valor: 'theme-celestial-gold', nome: 'Ouro Celestial' },
  { valor: 'theme-moonstone', nome: 'Pedra da Lua' },
  { valor: 'theme-cursed-ichor', nome: 'Ícor Amaldiçoado' },
  { valor: 'theme-chronos-sand', nome: 'Areia de Cronos' },
  { valor: 'theme-dreamweaver', nome: 'Tecelão de Sonhos' },
  { valor: 'theme-shadowfell', nome: 'Sombrio' },
  { valor: 'theme-cyberpunk-2077', nome: 'Cyberpunk' },
  { valor: 'theme-monochrome-hud', nome: 'HUD Monocromático' },
  { valor: 'theme-carbon-fiber', nome: 'Fibra de Carbono' },
  { valor: 'theme-plasma-reactor', nome: 'Reator de Plasma' },
  { valor: 'theme-circuit-board', nome: 'Placa de Circuito' },
  { valor: 'theme-liquid-mercury', nome: 'Mercúrio Líquido' },
  { valor: 'theme-industrial-hazard', nome: 'Risco Industrial' },
  { valor: 'theme-holographic-foil', nome: 'Holográfico' },
  { valor: 'theme-synthwave-sky', nome: 'Céu Synthwave' },
  { valor: 'theme-interstellar-warp', nome: 'Dobra Interestelar' },
  { valor: 'theme-sumie-ink', nome: 'Tinta Sumiê' },
  { valor: 'theme-vibrant-pop-art', nome: 'Pop Art Vibrante' },
  { valor: 'theme-watercolor-wash', nome: 'Aquarela' },
  { valor: 'theme-pixel-dungeon', nome: 'Masmorra Pixelada' },
  { valor: 'theme-gold-leaf', nome: 'Folha de Ouro' },
  { valor: 'theme-blueprint', nome: 'Planta Baixa' },
  { valor: 'theme-retro-comic', nome: 'Quadrinho Retrô' },
  { valor: 'theme-lava-lamp', nome: 'Luminária de Lava' },
  { valor: 'theme-stained-glass', nome: 'Vitral' },
  { valor: 'theme-chalkboard', nome: 'Lousa' },
  { valor: 'theme-candy-cane', nome: 'Bengalinha de Doce' },
  { valor: 'theme-galaxy-swirl', nome: 'Redemoinho Galáctico' },
  { valor: 'theme-royal-velvet', nome: 'Veludo Real' },
  { valor: 'theme-steampunk-brass', nome: 'Latão Steampunk' },
  { valor: 'theme-honey-hive', nome: 'Colmeia de Mel' },
  { valor: 'theme-triton-deep', nome: 'Abismo de Tritão' },
  { valor: 'theme-autumn-leaves', nome: 'Folhas de Outono' },
  { valor: 'theme-frozen-tundra', nome: 'Tundra Congelada' },
  { valor: 'theme-dragon-scale', nome: 'Escama de Dragão' },
]

export const TEMA_PADRAO = 'theme-glass'
